#!/bin/bash

file="/var/log/update_script.log"
if  ! crontab -l | grep -F "/home/user/init/scripting/02";
then
	crontab -l > mycron
	echo "0 4 * * 0 /home/user/init/scripting/02" >> mycron
	crontab mycron
	rm mycron
fi
if [ -f "$file" ]
then
	sudo chmod 777 "$file"
	sudo apt-get update >> "$file"
	sudo apt-get upgrade >> "$file"
else
	sudo touch "$file"
	sudo chmod 777 "$file"
	sudo apt-get update >> "$file"
	sudo apt-get upgrade >> "$file"
fi
