#!/bin/bash

if [ ! -f "md5" ]
then
	sudo touch md5
	sudo chmod 777 md5
	md5sum file | cut -d " " -f1 > md5
fi

if [ ! -f "md5_c" ]
then
	sudo touch md5_c
	sudo chmod 777 md5_c
fi

md5sum file | cut -d " " -f1 > md5_c

cmp -s md5_c md5 > /dev/null
if [ $? -eq 1 ]
then
	echo "difference"
	md5sum file | cut -d " " -f1 > md5
else
	echo "same"
fi
